spring:
  application:
    name: trade-notification-server
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    virtual-host: /
    listener:
      simple:
        concurrency: 2
        max-concurrency: 4
        prefetch: 2
        retry:
          enabled: true
  redis:
    host: localhost
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 3000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 4
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 2
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
  mail:
    host: smtp.qq.com
    port: 465
    username: contact@mail.moesome.com
    password: gibrrkglvetwbehc
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka,http://localhost:10002/eureka
  instance:
    prefer-ip-address: true
server:
  port: 23001

logging:
  level:
    com.moesome: debug